[package]
name = "raspivid-stream"
version = "0.1.0"
authors = ["ConcurrentMarxistGC <concurrentmarxistgc@users.noreply.github.com>"]

[dependencies]
lazy_static="*"
log="0.3"
env_logger="*"
serde="*"
serde_derive="*"
toml="0.4"
rocket = "^0.3.7"
rocket_codegen = "^0.3.7"
